### ISSUE TITLE
Research

### ISSUE THREAD

**Issue by mrjarbenne** [hwdsbcommons/saml-20-single-sign-on#5]
It looks like the Azure SSO solution I was hoping would solve our problems creates too many steps in the auth process to be as elegant as I had hoped (from Commons, to Azure, to our STS, then back).

So we are back to the SAML drawing board. I'm going to collect up some items that may be of use to us in making a better SAML plugin:

It looks as if this plugin doesn't necessarily require OneLogin: https://wordpress.org/plugins/onelogin-saml-sso/

https://github.com/onelogin/php-saml
https://github.com/tectonic/better-saml

**Comment by r-a-y** [comment]
I think the OneLogin plugin is a good start.  It doesn't support multisite from the looks of things.

We can either look at forking their WP plugin or use their PHP SAML library to build our own plugin.  I need to do a bit more research about how SAML works though.

**Comment by r-a-y** [comment]
This issue was moved to hwdsbcommons/HWDSB-Commons#43
